### ISSUE TITLE
Caching of static Assets in _headers

### ISSUE THREAD

**Issue by donaldboulton** [mmistakes/made-mistakes-gatsby#109]
I Like the new site. I went to using Gatsby in my site at [publiuslogic.com](https://publiuslogic.com/) 7 months before you published your Gatsby site I still have my old Jekyll site [donboulton.com](https://donboulton.com) that was based on Made Mistakes Jekyll.
Got curious of what you were doing and I learn through going through code and testing others sites.
In testing Made Mistakes Gatsby none of your static image assets are cached for longer than 5 days, these assets don't change so a year cache time would be ok.'caching for 5 days maybe for a reason ?', If not then you could add static caching in your _header file, "maybe a root _header file" for caching in just the /static/images/ folder or all static folders /static/* as below
`
/static/*
`
Images only
`
/static/images/
`
   Cache-Control = "public, max-age=31536000"
`
Nice Work like always!
Donald Boulton

**Comment by mmistakes** [comment]
Thanks. No particular reason on the caching. Just never got around to it I suppose.
