### ISSUE TITLE
Adding options for markdown, with initial focus on MathJax or KaTeX

### ISSUE THREAD

**Issue by griff-rees** [mmistakes/made-mistakes-gatsby#502]
First off: this is a brilliant project and thanks very much for providing it. I've dabbled with your other excellent static options and decided to try this one while diving into javascript (not a language I know... yet). Apologies in advance if I've made some _unhelpful_ mistakes (reference to name intended).

I'd like to add something like [MathJax](https://www.mathjax.org) or [KaTeX](https://katex.org) (probably the latter) and wondered the best approach for doing so while retaining compatibility for future contributions/merges as you update this repo. I can generate a pull request if that's helpful.

### Options I've tried so far

1. Make a pull request if you think KaTeX is a generally useful feature you'd like to include by default
2. Add a set of options within `config/site.js` which can be contingently added to `gatsby-browser.js`, `gatsby-config.js` and I guess by necessity `package.json` for generic modification
3. Use `gatsby-ssr.js` file using [KaTeX's API](https://katex.org/docs/api.html#server-side-rendering-or-rendering-to-a-string)

What I've got so far (following option 2) 

<img width="811" alt="Screenshot 2020-06-24 at 13 20 52" src="https://user-images.githubusercontent.com/60181741/85557995-3c97a000-b620-11ea-89c3-a17eb899bccd.png">

uses [gatspy-remark-katex](https://www.gatsbyjs.org/packages/gatsby-remark-katex/) and can render inline. There is a new version of MathJax [in development](http://docs.mathjax.org/en/latest/upgrading/v2.html) but I think KaTeX is a safer option at present.

**Comment by mmistakes** [comment]
Since I don't use MathJax at all on my site a PR adding support for it probably wouldn't be helpful.
As this repo is for my personal site and isn't a theme I'm going to go ahead and close it.

**Comment by griff-rees** [comment]
Thanks very much for the quick reply. I won't make any further suggestions. It's a very inspiring project and thanks very much for releasing it open source.
