### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by iColdPlayer** [mmistakes/made-mistakes-gatsby#70]
Hi,... First of all, thank's for making this beautiful theme.

I'm trying to understand what is going on with my code.

After I run `yarn install` command and want to run the project locally (like in the [readme](https://github.com/mmistakes/made-mistakes-gatsby/blob/master/README.md)), this error occurred.
```js
 ERROR 

UNHANDLED REJECTION Cannot read property 'match' of undefined



  TypeError: Cannot read property 'match' of undefined
  
  - api-runner-node-error-parser.js:39 errorParser
    [mdm]/[gatsby]/dist/utils/api-runner-node-error-parser.js:39:33
  
  - api-runner-node.js:398 
    [mdm]/[gatsby]/dist/utils/api-runner-node.js:398:29
  
  - api-runner-node.js:340 async module.exports
    [mdm]/[gatsby]/dist/utils/api-runner-node.js:340:18
  
  - source-nodes.js:86 async module.exports
    [mdm]/[gatsby]/dist/utils/source-nodes.js:86:3
  
  - index.js:406 async module.exports
    [mdm]/[gatsby]/dist/bootstrap/index.js:406:3
  
  - develop.js:407 async module.exports
    [mdm]/[gatsby]/dist/commands/develop.js:407:7
  
⠋ source and transform nodes
```

What do I miss here?

**Comment by mmistakes** [comment]
@iColdPlayer This isn't a theme... this is the source code for my personal website.

**Comment by iColdPlayer** [comment]
Ah, sorry, I mean I'm going to say that I love this source that you made for your personal blog.
Question is, can I also use this source for my personal blog?

**Comment by mmistakes** [comment]
Sure, you can use it as a starter. I'd hope you'd modify it enough to make it your own though.
